version: '3.8'
services:
  redis:
    image: 'redis:latest'
    container_name: redis_cse118-218
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis_cse118-218_data:/data'
    command:
      - redis-server
      - '--appendonly'
      - 'yes'
volumes:
  redis_cse118-218_data: null
